### ISSUE TITLE
Style issues with Safari

### ISSUE THREAD

**Issue by sdeleuze** [mixitconf/mixit#127]
With Safari 10 on Mac I observe this kind of CSS issues:

![image](https://cloud.githubusercontent.com/assets/141109/23265214/4a653a2c-f9e4-11e6-80cb-ee5e442e0649.png)

![image](https://cloud.githubusercontent.com/assets/141109/23265256/6548e7a8-f9e4-11e6-9cf0-f92142fda25b.png)

**Comment by clacote** [comment]
Still fucked up on latest desktop Safari.
