### ISSUE TITLE
Add speaker avatars

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#130]
That would require to have their email in DB to fetch their corresponding gravatar, but that would be warmer.

**Comment by sdeleuze** [comment]
We have the email hash in `logoUrl` so that should work. And in any case we need to import emails in PROD.

**Comment by sdeleuze** [comment]
We now use the `logoUrl` hash but hashes of new accounts are not in the db would be nice to generate and add them since we have not yet the emails in database.

**Comment by sdeleuze** [comment]
Done
