### ISSUE TITLE
Add html title meta data for each page

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#136]
- Page title per page. Something like:
  - Home: MiXiT -> MiXiT conférence
  - Sponsors: MiXiT -> MiXiT 2017 sponsors
  - Talks: MiXiT -> MiXiT 2017 talks
- Meta `description` per page

**Comment by clacote** [comment]
According to [Google Webmaster Tools](https://www.google.com/webmasters/tools/html-suggestions?hl=en&siteUrl=https://mixitconf.org/&probtype=9&pl=eyJ0YXJnZXRJZCI6Imh0bWwtc3VnZ2VzdGlvbnMiLCJwYXJhbXMiOnsic2l0ZVVybCI6Imh0dHBzOi8vbWl4aXRjb25mLm9yZy8iLCJobCI6ImVuIn19), several pages have a duplicate title:
- /2017/
- /
- /about/
- /en/2017/
- /en/
- /en/about/
- /en/blog/
- /en/sponsors/
- /sponsors/

**Comment by sdeleuze** [comment]
I will only manage `title` which is the more important one.
