### ISSUE TITLE
Add FAQ and details page

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#149]
- Price
- Ticketing policy
- Conference day details.
  - Agenda (start / end each day for transportation)
  - Food (vegan)
  - Drinks (coffee, water)
  - Video
  - Every interactive possibilities (votes, ...)
- How to come
- DIF/CFP
- Speakers:
  - accommodation
  - travel expenses

**Comment by mpetitdant** [comment]
Check the old website to retrieve Q&A

**Comment by clacote** [comment]
People start to ask for day details (when does it starts/ends, to plan their own transportation)

**Comment by clacote** [comment]
https://twitter.com/didier_broca/status/844859187423133698

**Comment by cbouttaz** [comment]
Shall we put these informations on the about page or add another entry in the menu ?

**Comment by clacote** [comment]
@cbouttaz: @doublejess does not like to multiply menu entries. So a new section in about page would be great. In fact anything that could make them public as soon as possible is the good way (we could then change later).
