### ISSUE TITLE
"---" (seen in URL as slugged title) is interpreted as rich syntax formatting

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#157]
https://mixitconf.org/blog/billetterie-mixit-2017---pre-inscription : this blog post as `---` in URL.
This is painful, because when pasted in a rich text editor (like Slack), the `---` is replaced by a long dash.
In markdown, this is for a line break: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#horizontal-rule

If possible, we should avoid using `---` in url.

**Comment by sdeleuze** [comment]
That would break all existing links so I am not in favor of that.

**Comment by clacote** [comment]
Of course, but the future ones could be generated without.

**Comment by sdeleuze** [comment]
Indeed

**Comment by clacote** [comment]
There is nothing to do, right? The _slug_ are manually set in the data, right? So we just have to keep that in mind. If yes, you're free to close.

**Comment by sdeleuze** [comment]
Not manually -> https://github.com/mixitconf/mixit/blob/master/src/main/kotlin/mixit/util/Extensions.kt#L106
