### ISSUE TITLE
Where is `org.springframework.web.reactive.function.server.router`?

### ISSUE THREAD

**Issue by kingsmiler** [mixitconf/mixit#168]
I'm new to here, and I follow the README.md guide, when I execute `gradle build` or `gradle bootRun`, I got the compiled error, like below:

![image](https://cloud.githubusercontent.com/assets/16532306/24086367/432efa4a-0d49-11e7-99b2-e2fcaf97dda3.png)

So,  where is `org.springframework.web.reactive.function.server.router` ? Thanks!

**Comment by sdeleuze** [comment]
Sorry about that Spring Framework snapshots are not built for a week due to an issue on our build server, it will be fixed shortly I will warn you.

**Comment by kingsmiler** [comment]
Understand, and thanks in advance!

**Comment by sdeleuze** [comment]
Snapshots are back, it should work again now.
