### ISSUE TITLE
Update talks_2017.json

### ISSUE THREAD

**Issue by cexbrayat** [mixitconf/mixit#178]
- [x] Mettre à jour tous les titres et descriptions avec export

Ajouter les horaires:
- [x] Paccard
- [x] lobbies/sabatier

Manque les talks:
- [x] Caroline Wair
- [x] trouvez vos cadences/gabrillargues
- [x] legacy club/pierrain
- [x] manque type theory/tavante ?

Workshops:
- [x] manque Mr Robot/jeanroy
- [x] remplacer ethereum (co-speaker cflamens)

Keynotes:
- [x] Nety et Mila
- [x] Qwant
- [x] Regen villages
- [x] Gonette

Horaires:
- [x] décaler les 2 journées de 10 minutes
- [x] insérer mini keynote 10 minutes Gonette
- [x] prendre en compte les nouvelles contraintes speakers de [Trello](https://trello.com/c/rsPUdiPH/167-planning-contraintes-non-traitees) et [gdoc](https://docs.google.com/spreadsheets/d/1nvWTJ2Xr0QE9OcDH58WTX7QQQlwNFtZ65ogkDIjlueU/edit#gid=0)

Random:
- [x] mettre le bon jour

Challenge:
- [x] hexagon challenge a faire figurer tout une journée (laquelle?)...

**Comment by sdeleuze** [comment]
CFP is closed so I guess the first step is to manually update title and description from CFP.io export to `talks_2017.json`.
