### ISSUE TITLE
Update homepage categories with CFP categories

### ISSUE THREAD

**Issue by sdeleuze** [mixitconf/mixit#179]
Greg propose we just use CFP categories (+ MixTeen)

**Comment by sdeleuze** [comment]
I have think about categories, here is the list I propose. I have made my best to limit the amount of different categories by merging Dev & Ops (I don't think that's a good idea to differentiate them) to Tech and removing Other (let's use Alien if no other category fit).

 - Aliens
 - Makers
 - Hacktivism
 - Tech
 - Product
 - Design
 - Team
 - Education
 - MixTeen

**Comment by sdeleuze** [comment]
I have updated categories to what should be the final version by merging team and education to learn.

**Comment by clacote** [comment]
\o/

**Comment by clacote** [comment]
Oops wrong PR. But this is nice too :) (will remove these comments)
