### ISSUE TITLE
[Come] More details about bike

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#219]
https://twitter.com/s_colson/status/850004500958130180:
> suggestion: manque section vélo (pas vélov) précisant qu'il y a arceaux au sol non abrités: https://mixitconf.org/come#bike

**Comment by StephaneColson** [comment]
Je crois que c'est fait, mais avec une belle faute à parqué (au lieu de parquer).

**Comment by sdeleuze** [comment]
Fixed
