### ISSUE TITLE
Historic talks are weirdly displayed

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#232]
When displaying an older event, the talks list is weird:
![image](https://cloud.githubusercontent.com/assets/750715/25617249/a0936c6a-2f41-11e7-871d-62d6625d8118.png)

It looks like:
- there are empty times displayed, consuming a lot of space
- it's in a single column instead of two (it's not weird to have a single column, but displayed attributes were specifically restricted to be displayed across two columns on desktop).
- day is sometimes displayed, sometimes not.

**Comment by sdeleuze** [comment]
Days are displayed if specified in DB so for 2016 for example you can just edit the talks and specify which day they happen. I will try to fix other glitches

**Comment by sdeleuze** [comment]
Hum I have not enabled yet backoffice for previous years, so I will try to fix 2016 data directly.

**Comment by sdeleuze** [comment]
Fixed
