### ISSUE TITLE
[FAQ] Legacy hashtag displayed as next edition one

### ISSUE THREAD

**Issue by dcarral** [mixitconf/mixit#263]
Currently under https://mixitconf.org/en/faq:

![screen shot 2018-01-07 at 01 09 46](https://user-images.githubusercontent.com/1498567/34645239-8d92db2a-f348-11e7-98f9-75ee8c705e9b.png)

Notice that the source locale (@ `src/main/resources/messages_en.properties`) has been already updated.

**Comment by javamind** [comment]
:+1:
