### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by sdeleuze** [mixitconf/mixit#30]
First version with:
 - Login form processing (manual for now since https://jira.spring.io/browse/SPR-15144 is not fixed yet)
 - Password hash stored in Mongo User JSON
 - `WebSession` based authentication

**Comment by javamind** [comment]
- [ ] authenth via Twitter
- [ ] authenth via Github
- [ ] authenth via Google
- [ ] old account importation

**Comment by javamind** [comment]
We have a simple process without oauth. A token is send by email to the user. If we want to do better we will open a new issue
