### ISSUE TITLE
Sponsors should be in footer of every page

### ISSUE THREAD

**Issue by clacote** [mixitconf/mixit#60]
The sponsors logos, as on the home page, should be in the footer of every page:
![image](https://cloud.githubusercontent.com/assets/750715/22760846/964914fa-ee58-11e6-84f4-93cb4599b907.png)

That would please our sponsors at no cost.

**Comment by javamind** [comment]
I'm not OK to add them on every page. Just on talk pages => Done
But I think it should be nice to add a feature to easily find the old sponsors with an URL like `hhtp://localhost:8080/2016/sponsors`

**Comment by javamind** [comment]
Done
